import Head from "next/head";
import React from "react";
import DrawerLayout from "@/components/app/DrawerLayout";
import NewOrderPage from "@/components/pages/NewOrderPage";

export default function NewOrder() {
  async function handleOrdersUpload(data) {
    console.log({ data });
    // const res = await writeData("Order", data);
    // if (!res?.error) {
    //   toast("User Added");
    // }
  }
  return (
    <DrawerLayout>
      <Head>
        <title>Place New Order</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewOrderPage handleOrdersUpload={handleOrdersUpload}  />
    </DrawerLayout>
  );
}
