import Head from "next/head";
import React, { useEffect, useRef, useState } from "react";
import "../styles/Home.module.css";
import HomePage from "@/components/pages/HomePage";
import DrawerLayout from "@/components/app/DrawerLayout";

export default function Home() {
  return (
    <DrawerLayout>
      <Head>
        <title>DM Fashion and Tailors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />
    </DrawerLayout>
  );
}
